# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InteractLearnDialog
                                 A QGIS plugin
 Framework to test the algos designed during my PhD
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-16
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Gaston Lenczner
        email                : gaston.lenczner@delair.aero
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from os.path import dirname

from PyQt5 import QtWidgets, uic
from PyQt5.QtWidgets import QFileDialog

from ..utils import find_file_from_layer, get_layers
from .layers_dialog import LayersDialog
from .cl_opts_dialog import CLDialog

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(os.path.dirname(__file__)), 'ui/interact_learn_dialog_base.ui'))


class InteractLearnDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface, parent=None):
        """Constructor."""
        super(InteractLearnDialog, self).__init__(parent)
        self.iface = iface
        self.sub_dlg = LayersDialog()
        self.dlg_cl = CLDialog()
        self.setupUi(self)
        self.button_conti.setEnabled(False)
        self.map_tool = None
        self.button_nn.clicked.connect(self.return_nn)
        self.button_output.clicked.connect(self.return_output)
        self.button_layers.clicked.connect(self.open_layers)
        self.button_conti.clicked.connect(self.open_cl_opt)
        self.checkBox_interactive.clicked.connect(self.hide_use_annot)
        self.checkBox_cl.clicked.connect(self.hide_cl_opts)

    def init_from_previous_state(self, files):
        self.checkBox_interactive.setCheckState(files["interactive"] * 2)
        self.checkBox_geojson.setCheckState(bool(files["polygonize"]) * 2)
        self.checkBox_ssh.setCheckState(files["ssh"] * 2)
        self.checkBox_cl.setCheckState(files["CL"] * 2)
        self.line_nn.setText(files["neural_network"])
        self.line_output.setText(files["output_file"])
        self.checkBox_use_annot.setCheckState(files["interact_use_annots"] * 2)
        self.button_conti.setEnabled(self.checkBox_cl.isChecked())

        self.dlg_cl.checkBox.setCheckState(files["cl_options"]["only_new_points"] * 2)
        self.dlg_cl.spinBox.setValue(files["cl_options"]["steps"])
        self.dlg_cl.spinBox_weight.setValue(files["cl_options"]["weight_reg"])
        self.dlg_cl.comboBox.setCurrentIndex(files["cl_options"]["reg_L1"])

        if files.get("input_files", False):
            layers, layer_list = get_layers()
            for i, layer in enumerate(layers):
                file = find_file_from_layer(layer)
                if file in files["input_files"]:
                    self.sub_dlg.listWidget.item(i).setSelected(True)
                    self.textEdit.setText(layer_list[i] + '\n')

    def return_nn(self):
        filename = QFileDialog.getOpenFileName(directory=dirname(self.line_nn.text()), filter="*.pt")[0]
        if filename:
            self.line_nn.setText(filename)

    def return_output(self):
        filename = QFileDialog.getSaveFileName(directory=dirname(self.line_output.text()))[0]
        if filename:
            self.line_output.setText(filename)

    def open_layers(self):
        result = self._open_dlg(self.sub_dlg)
        if result:
            self.textEdit.setText("\n".join([i.text() for i in self.sub_dlg.listWidget.selectedItems()]))
        else:
            self.textEdit.setText("")
            self.reload_rasters()

    def open_cl_opt(self):
        self._open_dlg(self.dlg_cl)

    def _open_dlg(self, dialog):
        dialog.show()
        result = dialog.exec_()
        return result

    def reload_rasters(self):
        """
        To load new possible rasters
        """
        self.sub_dlg = LayersDialog()

    def hide_use_annot(self):
        self.checkBox_use_annot.setEnabled(self.checkBox_interactive.isChecked())

    def hide_cl_opts(self):
        self.button_conti.setEnabled(self.checkBox_cl.isChecked())
